SELECT
L.EMPLOYEE_ID,
E.NAME AS 'Name',
E.PHONE_NUMBER AS 'Phone number',
E.CONTRACT_DATE AS 'Contract date',
COUNT(L.EMPLOYEE_ID) AS 'locations'
FROM LOCATIONS AS L
JOIN EMPLOYEES AS E ON L.EMPLOYEE_ID = E.ID
GROUP BY L.EMPLOYEE_ID
HAVING COUNT(L.EMPLOYEE_ID) >= 2;