SELECT
L.CUSTOMER_ID,
C.NAME AS 'Name',
C.LASTNAME AS 'Lastname',
C.PHONE AS 'Phone',
C.EMAIL AS 'Email',
C.ADDRESS AS 'Address',
C.CITY AS 'City',
C.STATE AS 'State',
C.BIRTH_DATE AS 'Birth date',
COUNT(L.CUSTOMER_ID) AS 'locations'
FROM LOCATIONS AS L
JOIN CUSTOMERS AS C ON L.CUSTOMER_ID = C.ID
GROUP BY L.CUSTOMER_ID
HAVING COUNT(L.CUSTOMER_ID) >= 2;